// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AliPlayer: typeof import('./src/components/video/AliPlayer.vue')['default']
    DPlayer: typeof import('./src/components/video/dPlayer.vue')['default']
    EasyWasmPlayer: typeof import('./src/components/video/EasyWasmPlayer.vue')['default']
    GoldPlay: typeof import('./src/components/video/GoldPlay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JessIbuca: typeof import('./src/components/video/JessIbuca.vue')['default']
    PopupsDemo: typeof import('./src/components/PopupsDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanTag: typeof import('vant/es')['Tag']
    VideoJs: typeof import('./src/components/video/videoJs.vue')['default']
  }
}
